/**
 * Automated Release Publisher for Kiraeve TikTok
 * Guarantees that latest.yml, installer exe, and blockmap are always uploaded and verified on GitHub Releases.
 * Prevents "Cannot find latest.yml in the latest release artifacts" error forever.
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const rootDir = path.resolve(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf-8'));
const version = pkg.version;
const tag = `v${version}`;
const distDir = path.join(rootDir, 'dist');
const singleOutputDir = path.join(distDir, 'Single-File-For-Customer');

console.log(`\n=======================================================`);
console.log(`[Release Publisher] Building & Publishing ${tag}...`);
console.log(`=======================================================\n`);

// Step 0: Clean old builds in dist to eliminate multiple old files
if (fs.existsSync(distDir)) {
    console.log('[Release Publisher] Step 0: Cleaning old build files in dist/ to keep directory clean...');
    const existing = fs.readdirSync(distDir);
    for (const f of existing) {
        if (f.endsWith('.exe') || f.endsWith('.blockmap') || f.endsWith('.yml')) {
            try {
                fs.unlinkSync(path.join(distDir, f));
            } catch (_) {}
        }
    }
}

// Step 1: Ensure dist directory exists and build Windows target
console.log('[Release Publisher] Step 1: Building with electron-builder...');
execSync('npx electron-builder --win --publish never', { cwd: rootDir, stdio: 'inherit' });

// Step 2: Validate dist/latest.yml
const distDir = path.join(rootDir, 'dist');
const latestYmlPath = path.join(distDir, 'latest.yml');
if (!fs.existsSync(latestYmlPath)) {
    console.error('[ERROR] dist/latest.yml was not generated by electron-builder!');
    process.exit(1);
}

const latestYmlContent = fs.readFileSync(latestYmlPath, 'utf-8');
console.log('[Release Publisher] Step 2: Validated dist/latest.yml:\n' + latestYmlContent.trim());

// Step 3: Ensure both space-separated and dashed exe names exist and are ALWAYS in sync
const spaceExe = path.join(distDir, `Kiraeve TikTok Setup ${version}.exe`);
const dashExe = path.join(distDir, `Kiraeve-TikTok-Setup-${version}.exe`);

if (fs.existsSync(spaceExe)) {
    fs.copyFileSync(spaceExe, dashExe);
    console.log(`[Release Publisher] Synced fresh alias: ${dashExe}`);
} else if (fs.existsSync(dashExe)) {
    fs.copyFileSync(dashExe, spaceExe);
    console.log(`[Release Publisher] Synced fresh alias: ${spaceExe}`);
}

const spaceBlockmap = path.join(distDir, `Kiraeve TikTok Setup ${version}.exe.blockmap`);
const dashBlockmap = path.join(distDir, `Kiraeve-TikTok-Setup-${version}.exe.blockmap`);
if (fs.existsSync(spaceBlockmap)) {
    fs.copyFileSync(spaceBlockmap, dashBlockmap);
} else if (fs.existsSync(dashBlockmap)) {
    fs.copyFileSync(dashBlockmap, spaceBlockmap);
}

// Step 3.5: Cryptographic checksum validation against latest.yml
const primaryExe = fs.existsSync(dashExe) ? dashExe : spaceExe;
const fileHash = crypto.createHash('sha512').update(fs.readFileSync(primaryExe)).digest('base64');
console.log(`[Release Publisher] Calculated sha512 for ${path.basename(primaryExe)}:\n  ${fileHash}`);

if (!latestYmlContent.includes(fileHash)) {
    console.error(`[CRITICAL ERROR] sha512 mismatch! latest.yml does not match ${path.basename(primaryExe)}!`);
    process.exit(1);
}
console.log('[Release Publisher] Verified sha512 checksum matches latest.yml 100%!');

// Step 4: Create single-file folder for user to send directly to customer
if (!fs.existsSync(singleOutputDir)) {
    fs.mkdirSync(singleOutputDir, { recursive: true });
}
const customerFile = path.join(singleOutputDir, `Kiraeve-TikTok-Setup-${version}.exe`);
fs.copyFileSync(primaryExe, customerFile);
console.log(`\n[Release Publisher] Isolated single customer file ready:`);
console.log(`  -> ${customerFile}\n`);

// Step 5: Collect assets to upload
const assetsToUpload = [latestYmlPath];
if (fs.existsSync(dashExe)) assetsToUpload.push(dashExe);
if (fs.existsSync(spaceExe)) assetsToUpload.push(spaceExe);
if (fs.existsSync(dashBlockmap)) assetsToUpload.push(dashBlockmap);
if (fs.existsSync(spaceBlockmap)) assetsToUpload.push(spaceBlockmap);

console.log(`[Release Publisher] Step 5: Assets to upload (${assetsToUpload.length} files):`);
assetsToUpload.forEach(a => console.log('  - ' + path.basename(a)));

// Step 6: Check if GitHub release tag exists
let releaseExists = false;
try {
    execSync(`gh release view ${tag}`, { cwd: rootDir, stdio: 'ignore' });
    releaseExists = true;
} catch (e) {
    releaseExists = false;
}

const filesArgs = assetsToUpload.map(f => `"${f}"`).join(' ');
if (!releaseExists) {
    console.log(`[Release Publisher] Step 6: Creating GitHub release ${tag}...`);
    execSync(`gh release create ${tag} ${filesArgs} --title "${tag} - Kiraeve TikTok" --notes "Release ${tag}: Fix TikTok LIVE connection freeze, remove flickering, and optimize event handling."`, {
        cwd: rootDir,
        stdio: 'inherit'
    });
} else {
    console.log(`[Release Publisher] Step 6: Release ${tag} exists. Uploading/clobbering assets...`);
    execSync(`gh release upload ${tag} ${filesArgs} --clobber`, {
        cwd: rootDir,
        stdio: 'inherit'
    });
}

// Step 7: Verify latest.yml on GitHub Releases with HTTP GET
console.log('[Release Publisher] Step 7: Verifying latest.yml on GitHub for in-app Auto-Updater...');
const checkUrl = `https://github.com/KittinanDev/kiraeve-tiktok/releases/download/${tag}/latest.yml`;

function verifyOnlineYml(retries = 6) {
    return new Promise((resolve, reject) => {
        const attempt = (left) => {
            https.get(checkUrl, { headers: { 'User-Agent': 'Kiraeve-Release-Verifier' } }, (res) => {
                if (res.statusCode === 200 || res.statusCode === 302) {
                    console.log(`[Release Publisher] SUCCESS: latest.yml verified online (Status: ${res.statusCode})`);
                    resolve();
                } else if (left > 0) {
                    console.warn(`[Release Publisher] Waiting for GitHub CDN propagation (Status: ${res.statusCode}), retrying in 3s...`);
                    setTimeout(() => attempt(left - 1), 3000);
                } else {
                    reject(new Error(`Failed to verify latest.yml on GitHub: HTTP ${res.statusCode}`));
                }
            }).on('error', (err) => {
                if (left > 0) {
                    setTimeout(() => attempt(left - 1), 3000);
                } else {
                    reject(err);
                }
            });
        };
        attempt(retries);
    });
}

verifyOnlineYml().then(() => {
    console.log(`\n=======================================================`);
    console.log(`[RELEASE SUCCESS] ${tag} published with verified latest.yml!`);
    console.log(`[READY TO SEND] ไฟล์ตัวติดตั้งตัวเดียวสำหรับส่งให้ลูกค้า:`);
    console.log(`  -> ${customerFile}`);
    console.log(`=======================================================\n`);
    process.exit(0);
}).catch((err) => {
    console.error(`\n[CRITICAL ERROR] Release verification failed:`, err.message);
    process.exit(1);
});
